name: mergeonMondy
on:
  schedule:
    - cron: "0-3 0 * * MON"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          MERGE_METHOD: "squash" 
